# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# last update @srija-ieee

title: TWISHA 
email:
description: >- # this means to ignore newlines until "baseurl:"
Twisha, or The Women In Self-Health Awareness, is a project by GramSheel Foundation.

The scope of Project Twisha include women’s health issues (direct objective), child health issues (parallel objective), and domestic health issues (indirect objective targeting alcoholism, sanitation, water etc.)

Twisha designs kits for assessing self-health, related books, and simple health packets (containing PCC etc.). The media initiatives under Twisha produce blogs, articles, and tweets. Along with this Twisha trains volunteers as self-health awareness enablers. Twisha also produces videos covering expert advice and panel discussions or events related to women’s health issues.

Twisha’s activities include and are based on strong research and development (R&D). This primarily concerns medical research on women’s health issues and medical devices / telemedicine for women.

Disclaimer: This is being shared for academic and information purposes only. There is no guarantee or liability of any kind or consideration. There is no claim to accuracy or fitment for any purpose.
twitter_username: username
github_username: username
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: projectvikram/vikramtheme
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: IST # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "TWISHA "
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "The Women in Self Health Awarness"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/projectvikram/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/Twisha-384439938650057"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/twisha"

footer:
  links:
    - label: "Advisors"
      icon: "fas fa-fw fa-award"
      url: "/advisors/"
    - label: "Team"
      icon: "fas fa-fw fa-users-cog"
      url: "/team/"
    - label: "Partners"
      icon: "fas fa-fw fa-handshake"
      url: "/partners/"
    - label: "License"
      icon: "fas fa-fw fa-file-contract"
      url: "/license/"
    - label: "Privacy Policy"
      icon: "fas fa-fw fa-mask"
      url: "/privacy/"
    - label: "Term & Conditions"
      icon: "fas fa-fw fa-balance-scale-right"
      url: "/terms/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

